# Generated by Django 5.2.8 on 2025-11-06 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_tb_category_tb_book_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='tb_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8)),
            ],
        ),
        migrations.RenameField(
            model_name='tb_user',
            old_name='name',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='tb_book',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.tb_author'),
        ),
        migrations.CreateModel(
            name='tb_book_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_isbn', models.CharField(max_length=13)),
                ('estado_fisico', models.CharField(max_length=100)),
                ('estado_prestamo', models.BooleanField()),
                ('libro_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.tb_book')),
            ],
        ),
        migrations.CreateModel(
            name='tb_loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('comentarios', models.CharField(max_length=200)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.tb_book_detail')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.tb_student')),
            ],
        ),
    ]
